syms s func_transf_correnteRede_tensaoFiltro ...
    tensao_barramento tensao_rede_linha_rms ...
    corrente_rede_base corrente_rede_thd ...
    pot_rede_aparente fp_rede ...
    capacitor_filtro indutancia_filtro r_capacitores r_indutores ...
    indutancia_rede indutancia_rede_base indutancia_total indutancia_total_pu ...
    freq_chave freq_rede freq_resso omega_rede omega_resso ... 
    r_freq_chave_rede r_freq_chave_resso

format shortEng;
sdisp = @(x) strtrim(evalc(sprintf('disp(%g)', x)));

tarefa_5_2_dimensionamento;

indutancia_filtro_calc = eval(subs(indutancia_filtro, ... 
    [pot_rede_aparente, tensao_rede_linha_rms, freq_rede, freq_chave, tensao_barramento], ...
    [20e3, 380, 60, 6000, 700]));

indutancia_rede_calc = eval(subs(indutancia_rede, ... 
    [pot_rede_aparente, tensao_rede_linha_rms, freq_rede, freq_chave, tensao_barramento], ...
    [20e3, 380, 60, 6000, 700]));

capacitor_filtro_calc = eval(subs(capacitor_filtro, ... 
    [pot_rede_aparente, tensao_rede_linha_rms, freq_rede, freq_chave, tensao_barramento], ...
    [20e3, 380, 60, 6000, 700]));

fp_rede_calc = eval(subs(fp_rede, ... 
    [pot_rede_aparente, tensao_rede_linha_rms, freq_rede, freq_chave, tensao_barramento], ...
    [20e3, 380, 60, 6000, 700]));

freq_resso_calc = eval(subs(freq_resso, ... 
    [pot_rede_aparente, tensao_rede_linha_rms, freq_rede, freq_chave, tensao_barramento], ...
    [20e3, 380, 60, 6000, 700]));

corrente_rede_thd_calc = eval(subs(corrente_rede_thd, ... 
    [pot_rede_aparente, tensao_rede_linha_rms, freq_rede, freq_chave, tensao_barramento], ...
    [20e3, 380, 60, 6000, 700]));  

fprintf('Indutor do filtro [H]: %s \n', sdisp(indutancia_filtro_calc));
fprintf('Indutor da rede [H]: %s \n', sdisp(indutancia_rede_calc));
fprintf('Capacitor do filtro [F]: %s \n', sdisp(capacitor_filtro_calc));
fprintf('Freq. de  ressonancia [Hz]: %s \n', sdisp(freq_resso_calc));
fprintf('Fator de potencia da rede: %s \n', sdisp(fp_rede_calc));
fprintf('THD da rede []: %s \n', sdisp(corrente_rede_thd_calc*100));

tarefa_5_2_func_transf;
